// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 4.8
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_basic_linear(c,a,b){var d=jQuery;var e=d("<div></div>").css({position:"absolute",display:"none","z-index":2,width:"200%",height:"100%"}).appendTo(b);this.go=function(f,j){e.stop(1,1);var g=(!!((f-j+1)%a.length)^c.revers?"left":"right");d(a[j]).clone().css({position:"absolute",left:"auto",right:"auto",top:0,width:"50%"}).appendTo(e).css(g,0);d(a[f]).clone().css({position:"absolute",left:"auto",right:"auto",top:0,width:"50%"}).appendTo(e).css(g,"50%").show();e.css({left:"auto",right:"auto",top:0}).css(g,0).show();var h=b.find("ul").hide();var i={};i[g]="-100%";e.animate(i,c.duration,"easeInOutExpo",function(){h.css({left:-f+"00%"}).show();d(this).hide().html("")});return f}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 4.8
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"basic_linear",prev:"",next:"",duration:20*100,delay:20*100,width:860,height:1113,autoPlay:false,playPause:false,stopOnHover:false,loop:false,bullets:0,caption:false,captionEffect:"slide",controls:true,onBeforeStep:0,images:[{src:"./artoflego_page_01.jpg",title:"artoflego_Page_01"%6},{src:"./artoflego_page_02.jpg",title:"artoflego_Page_02"%6},{src:"./artoflego_page_03.jpg",title:"artoflego_Page_03"%6},{src:"./artoflego_page_04.jpg",title:"artoflego_Page_04"%6},{src:"./artoflego_page_05.jpg",title:"artoflego_Page_05"%6},{src:"./artoflego_page_06.jpg",title:"artoflego_Page_06"%6},{src:"./artoflego_page_07.jpg",title:"artoflego_Page_07"%6},{src:"./artoflego_page_08.jpg",title:"artoflego_Page_08"%6},{src:"./artoflego_page_09.jpg",title:"artoflego_Page_09"%6},{src:"./artoflego_page_10.jpg",title:"artoflego_Page_10"%6},{src:"./artoflego_page_11.jpg",title:"artoflego_Page_11"%6},{src:"./artoflego_page_12.jpg",title:"artoflego_Page_12"%6},{src:"./artoflego_page_13.jpg",title:"artoflego_Page_13"%6},{src:"./artoflego_page_14.jpg",title:"artoflego_Page_14"%6},{src:"./artoflego_page_15.jpg",title:"artoflego_Page_15"%6},{src:"./artoflego_page_16.jpg",title:"artoflego_Page_16"%6},{src:"./artoflego_page_17.jpg",title:"artoflego_Page_17"%6},{src:"./artoflego_page_18.jpg",title:"artoflego_Page_18"%6},{src:"./artoflego_page_19.jpg",title:"artoflego_Page_19"%6}]});