// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 4.8
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_basic_linear(c,a,b){var d=jQuery;var e=d("<div></div>").css({position:"absolute",display:"none","z-index":2,width:"200%",height:"100%"}).appendTo(b);this.go=function(f,j){e.stop(1,1);var g=(!!((f-j+1)%a.length)^c.revers?"left":"right");d(a[j]).clone().css({position:"absolute",left:"auto",right:"auto",top:0,width:"50%"}).appendTo(e).css(g,0);d(a[f]).clone().css({position:"absolute",left:"auto",right:"auto",top:0,width:"50%"}).appendTo(e).css(g,"50%").show();e.css({left:"auto",right:"auto",top:0}).css(g,0).show();var h=b.find("ul").hide();var i={};i[g]="-100%";e.animate(i,c.duration,"easeInOutExpo",function(){h.css({left:-f+"00%"}).show();d(this).hide().html("")});return f}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 4.8
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"basic_linear",prev:"",next:"",duration:19*100,delay:15*100,width:960,height:720,autoPlay:false,playPause:false,stopOnHover:false,loop:false,bullets:0,caption:false,captionEffect:"slide",controls:true,onBeforeStep:0,images:[{src:"./slide1.jpg",title:"Slide1"%6},{src:"./slide2.jpg",title:"Slide2"%6},{src:"./slide3.jpg",title:"Slide3"%6},{src:"./slide4.jpg",title:"Slide4"%6},{src:"./slide5.jpg",title:"Slide5"%6},{src:"./slide6.jpg",title:"Slide6"%6},{src:"./slide7.jpg",title:"Slide7"%6},{src:"./slide8.jpg",title:"Slide8"%6},{src:"./slide9.jpg",title:"Slide9"%6},{src:"./slide10.jpg",title:"Slide10"%6},{src:"./slide11.jpg",title:"Slide11"%6},{src:"./slide12.jpg",title:"Slide12"%6},{src:"./slide13.jpg",title:"Slide13"%6},{src:"./slide14.jpg",title:"Slide14"%6},{src:"./slide15.jpg",title:"Slide15"%6},{src:"./slide16.jpg",title:"Slide16"%6},{src:"./slide17.jpg",title:"Slide17"%6},{src:"./slide18.jpg",title:"Slide18"%6},{src:"./slide19.jpg",title:"Slide19"%6},{src:"./slide20.jpg",title:"Slide20"%6},{src:"./slide21.jpg",title:"Slide21"%6},{src:"./slide22.jpg",title:"Slide22"%6}]});