// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 4.8
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_basic_linear(c,a,b){var d=jQuery;var e=d("<div></div>").css({position:"absolute",display:"none","z-index":2,width:"200%",height:"100%"}).appendTo(b);this.go=function(f,j){e.stop(1,1);var g=(!!((f-j+1)%a.length)^c.revers?"left":"right");d(a[j]).clone().css({position:"absolute",left:"auto",right:"auto",top:0,width:"50%"}).appendTo(e).css(g,0);d(a[f]).clone().css({position:"absolute",left:"auto",right:"auto",top:0,width:"50%"}).appendTo(e).css(g,"50%").show();e.css({left:"auto",right:"auto",top:0}).css(g,0).show();var h=b.find("ul").hide();var i={};i[g]="-100%";e.animate(i,c.duration,"easeInOutExpo",function(){h.css({left:-f+"00%"}).show();d(this).hide().html("")});return f}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 4.8
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"basic_linear",prev:"",next:"",duration:20*100,delay:20*100,width:960,height:720,autoPlay:false,playPause:false,stopOnHover:false,loop:false,bullets:0,caption:false,captionEffect:"slide",controls:true,onBeforeStep:0,images:[{src:"./slide1.jpg",title:"slide1"%6},{src:"./slide2.jpg",title:"slide2"%6},{src:"./slide3.jpg",title:"slide3"%6},{src:"./slide4.jpg",title:"slide4"%6},{src:"./slide5.jpg",title:"slide5"%6},{src:"./slide6.jpg",title:"slide6"%6},{src:"./slide7.jpg",title:"slide7"%6},{src:"./slide8.jpg",title:"slide8"%6},{src:"./slide9.jpg",title:"slide9"%6},{src:"./slide10.jpg",title:"slide10"%6},{src:"./slide11.jpg",title:"slide11"%6},{src:"./slide12.jpg",title:"slide12"%6},{src:"./slide13.jpg",title:"slide13"%6},{src:"./slide14.jpg",title:"slide14"%6},{src:"./slide15.jpg",title:"slide15"%6},{src:"./slide16.jpg",title:"slide16"%6},{src:"./slide17.jpg",title:"slide17"%6},{src:"./slide18.jpg",title:"slide18"%6},{src:"./slide19.jpg",title:"slide19"%6},{src:"./slide20.jpg",title:"slide20"%6},{src:"./slide21.jpg",title:"slide21"%6},{src:"./slide22.jpg",title:"slide22"%6},{src:"./slide23.jpg",title:"slide23"%6},{src:"./slide24.jpg",title:"slide24"%6},{src:"./slide25.jpg",title:"slide25"%6},{src:"./slide26.jpg",title:"slide26"%6},{src:"./slide27.jpg",title:"slide27"%6},{src:"./slide28.jpg",title:"slide28"%6},{src:"./slide29.jpg",title:"slide29"%6}]});